### ISSUE TITLE
FastVPINNs: Github actions yaml file

### ISSUE THREAD

**Issue by thivin-zenteiq-ai** [zenoxml/SciREX#9]
The tests in [PR#8](https://github.com/zenoxml/SciREX/pull/8) are failing 

 in File "code-quality-control.yml" and "unit-tests.yml" file , the python version is mentioned as

```yaml
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

```

However, the unit test is picking them as version 3.1 instead of 3.10, which makes the tests to fail  

![image](https://github.com/user-attachments/assets/ee743e5f-f80f-4829-9624-9b87c7b0c230)
